#!/bin/bash
#
# Copyright (c) 2016 Western Digital Corporation or its affiliates
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.

scriptdir=$(dirname "$0")

# shellcheck source=lib/functions
. "$scriptdir/lib/functions"

# Verify whether all required software has been installed
pre_check() {
    for e in fio mkfs.ext4 mkfs.xfs multipathd pidof sg_reset; do
	if ! type -P "$e" >/dev/null 2>&1; then
	    echo "Error: could not find $e"
	    return 1
	fi
    done
}


# Set up test configuration
setup() {
    if ! pidof multipathd >/dev/null; then
	echo "Error: multipathd is not running"
	return 1
    fi

    /etc/init.d/srpd stop >/dev/null 2>&1
    if pidof srp_daemon >/dev/null; then
	echo "Error: failed to stop srp_daemon"
	return 1
    fi

    teardown || return $?

    for m in ; do
        echo module $m +pmf >/sys/kernel/debug/dynamic_debug/control
    done

    start_target || return $?

    use_blk_mq y y || return $?

    start_client ""
}

# Undo setup()
teardown() {
    remove_mpath_devs &&
    log_out &&
    stop_client &&
    stop_target
}

# Run the actual SRP tests
run_tests() {
    local success=0 failure=0 i t

    if [ ${#tests[@]} = 0 ]; then
	for t in "$scriptdir/tests"/*; do
	    tests+=("$t")
	done
    else
	for ((i=0;i<${#tests[@]};i++)); do
	    tests[i]="$scriptdir/tests/${tests[i]}"
	done
    fi
    for t in "${tests[@]}"; do
	[ "${t%\~}" != "$t" ] && continue
	echo "Running test $t ..."
	if "$t" "${options[@]}"; then
	    echo "Test $t succeeded"
	    ((success++))
	else
	    echo "Test $t failed"
	    ((failure++))
	    if [ -n "$debug" ]; then
		return 1
	    fi
	fi
    done
    echo "$success tests succeeded and $failure tests failed"
}

parse_cmdline "$@" &&
    pre_check &&
    setup &&
    {
	run_tests &&
	teardown
    }
