#!/bin/bash
#
# Copyright (c) 2016 Western Digital Corporation or its affiliates
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.

# shellcheck source=lib/functions
. "$(dirname "$0")/../lib/functions"

test_large_transfer_size() {
    local dev m

    echo "Test large transfer sizes"
    srp_log_out
    srp_log_in "queue_size=32,max_cmd_per_lun=32,max_sect=8192"
    dev=$(get_bdev 0) || return $?
    run_fio --verify=md5 -rw=randwrite --size=16M --bs=4M --loops=$((10**6)) \
	--iodepth=4 --group_reporting --sync=1 --direct=1 --ioengine=libaio \
	--filename="$dev" --name=large-io-test --thread --numjobs=1 \
	--runtime=10 --output=fio-output-03.txt >/dev/null
}

parse_cmdline "$@" &&
    test_large_transfer_size
